// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/feed/feed.proto

/*
Package rallybargain_srv_feed is a generated protocol buffer package.

It is generated from these files:
	proto/feed/feed.proto

It has these top-level messages:
	Feed
	Request
	Response
*/
package rallybargain_srv_feed

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for FeedService service

type FeedServiceClient interface {
	Create(ctx context.Context, in *Feed, opts ...client.CallOption) (*Response, error)
	GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type feedServiceClient struct {
	c           client.Client
	serviceName string
}

func NewFeedServiceClient(serviceName string, c client.Client) FeedServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "rallybargain.srv.feed"
	}
	return &feedServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *feedServiceClient) Create(ctx context.Context, in *Feed, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "FeedService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedServiceClient) GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "FeedService.GetAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FeedService service

type FeedServiceHandler interface {
	Create(context.Context, *Feed, *Response) error
	GetAll(context.Context, *Request, *Response) error
}

func RegisterFeedServiceHandler(s server.Server, hdlr FeedServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&FeedService{hdlr}, opts...))
}

type FeedService struct {
	FeedServiceHandler
}

func (h *FeedService) Create(ctx context.Context, in *Feed, out *Response) error {
	return h.FeedServiceHandler.Create(ctx, in, out)
}

func (h *FeedService) GetAll(ctx context.Context, in *Request, out *Response) error {
	return h.FeedServiceHandler.GetAll(ctx, in, out)
}
