version: '3.1'

services:
  database:
    image: postgres
    ports:
      - 3306:3306
  feed_service:
    build: ./feed_service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    
    depends_on:
      - database
  
  feed_cli:
    build: ./feed_cli
    environment:
      MICRO_REGISTRY: "mdns"